dist: trusty
sudo: false
language: node_js
node_js:
  - '12'
addons:
  chrome: stable
cache:
  directories:
    - './node_modules'
install:
  - npm install
before_script:
  - npm install -g @ionic/cli
script:
  - npm run prebuild
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    ionic build --configuration=staging;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ionic build --configuration=production;
    fi
before_deploy:
  - (cd functions && npm install)
deploy:
  - provider: firebase
    skip_cleanup: true
    message: Deploying LeCoinDuProf to STAGING
    project: default
    token:
      secure: 'T+Jq2ru3k5N1UWjIqdbYfrus8O7sASwk9S1UeLbGrLWr0aCprLwq5BTxv93MK8F07tgEJ60gDP3dgGnXoueo34KO2TBTUDontWt3RpNETbefuO0MU4RZDDg6hxJVnvQ1QKfUT1rn4oJVahh6wQbF7+yjNKlbzQGs4A3HdkrZa9l1+PP06LVsJwQmULmjVtRXJzJEdC6/raIyhbpUEzER+4XUT7cdYEy2WghaI2WQeLHKJCxle4Kn+zmM9YOFsYs1Y1r491yqZMF+1wU+dj825j2jks2iDVRPImSrfONHMcwAc3nKz4wAYSk7X8jsai6qXVdSCBDHOUqc3BbcutQ+D9T3eyfztTVQ3Z4SVzdAWuA5x8dFLGqwFDhp0+K9BFGNLBXQUQ+8xuOLwiJYxPuBI3LV4eAeM2W7GdKFNlHmqLHu4gEUtZSpV98ysDGvQ3/STH5FBfoK3spbnD3tRZmKby5JZFznJz5ELeyiOua9jSNig0cQKyeifhmPVsOVUvEquCx7Hvau1BWou94LXI3CITNTMAQZYlUph8FYUMhVYd2PS2glSROGY3s/gZnN6gso6LJ74JqC3hNkl4Owc2rKrjm9tyGZ0wMcZ3LSosFgQhC2DgIkhWtCHKRUfxA2If0J2g74v3ush4q6PUtp3PKXYRe0hJJ9OkTXmJZHVfZukd8='
    on:
      branch: develop
  - provider: firebase
    message: Deploying LeCoinDuProf to PRODUCTION
    skip_cleanup: true
    project: production
    token:
      secure: 'T+Jq2ru3k5N1UWjIqdbYfrus8O7sASwk9S1UeLbGrLWr0aCprLwq5BTxv93MK8F07tgEJ60gDP3dgGnXoueo34KO2TBTUDontWt3RpNETbefuO0MU4RZDDg6hxJVnvQ1QKfUT1rn4oJVahh6wQbF7+yjNKlbzQGs4A3HdkrZa9l1+PP06LVsJwQmULmjVtRXJzJEdC6/raIyhbpUEzER+4XUT7cdYEy2WghaI2WQeLHKJCxle4Kn+zmM9YOFsYs1Y1r491yqZMF+1wU+dj825j2jks2iDVRPImSrfONHMcwAc3nKz4wAYSk7X8jsai6qXVdSCBDHOUqc3BbcutQ+D9T3eyfztTVQ3Z4SVzdAWuA5x8dFLGqwFDhp0+K9BFGNLBXQUQ+8xuOLwiJYxPuBI3LV4eAeM2W7GdKFNlHmqLHu4gEUtZSpV98ysDGvQ3/STH5FBfoK3spbnD3tRZmKby5JZFznJz5ELeyiOua9jSNig0cQKyeifhmPVsOVUvEquCx7Hvau1BWou94LXI3CITNTMAQZYlUph8FYUMhVYd2PS2glSROGY3s/gZnN6gso6LJ74JqC3hNkl4Owc2rKrjm9tyGZ0wMcZ3LSosFgQhC2DgIkhWtCHKRUfxA2If0J2g74v3ush4q6PUtp3PKXYRe0hJJ9OkTXmJZHVfZukd8='
    on:
      branch: master
