dist: trusty
sudo: false
language: node_js
node_js:
  - '11'
addons:
  chrome: stable
cache:
  directories:
    - './node_modules'
install:
  - npm install
before_script:
  - npm install -g ionic
script:
  # - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox --code-coverage
  # - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  # Inject CI's env variables into environment.prod.ts to keep environment variables secret
  - npm run prebuild
  - ionic build --prod
