dist: trusty
sudo: false
language: node_js
node_js:
  - '12'
addons:
  chrome: stable
cache:
  directories:
    - './node_modules'
install:
  - npm install
before_script:
  - npm install -g @ionic/cli
script:
  - npm run prebuild
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    ionic build --configuration=staging;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ionic build --configuration=production;
    fi
before_deploy:
  - (cd functions && npm install)
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    message: Deploying LeCoinDuProf to STAGING
    project: default
    token:
      secure: kJTS5TeabxdCERKq2Q0/wWDQ4Xx1jHPcw1qzkMNaK5TlBGwCuMMWr/7Lyzv//gk1jgz+yFpR/IuefOMk8GAx56DDv3ArhOSzQq0O3cg2sl9b5B4tHU7tDBuhI38vqbnx5vAgOjfURfBLniZWX+eSJ2Mp8Z5uS+rBCbnBktEY/KPeRx5DCSDFU39SoDx6oinlMb5FPlONhfJ9xIVBb23S/8kMz6aP5Tu9ibE2W0IFUGE2emwSafIboXmpw/xzktlji0a/VLTYd1mTjZ58aXYpPRLl/voVz/NF9yxzpI4kH9guCuGr6Mww4SCeH1oUL2iAe4JKalkZmK2QW9qq5XCeB7v2gPsfgwTKVv/vwnhy5gL5QdGt7+BTrD7Gs8wE8SppEPSTPOUgt1FA1Fk2XgF0HkVAaqHVOa8pBx2rNcJ26CjnvIPRvz0YNd84nwkf1yUXI6C8ecdj8tJv3VhY4vQCvMEsrZa6Pqxh1SmzkmW6HK1zEHd7keQuscpturKEdfJd4gK9EH6XTG/3B2fzqlo251rbtXMUpqaf9bLvpGAEEGHmH6Vovuu0YIHbiynUbKg0g3aptB56zQWtmqdI5fsPdE23laFrBQv+W+CQzEYgLaI2ekvneccFJ700c1naOjEcZ94Oi2S2Kn+5TDIr13rlRYA+q5gYFhlRRDrMl1Jx35Y=
    on:
      branch: develop
  - provider: firebase
    message: Deploying LeCoinDuProf to PRODUCTION
    skip_cleanup: true
    project: production
    token:
      secure: kJTS5TeabxdCERKq2Q0/wWDQ4Xx1jHPcw1qzkMNaK5TlBGwCuMMWr/7Lyzv//gk1jgz+yFpR/IuefOMk8GAx56DDv3ArhOSzQq0O3cg2sl9b5B4tHU7tDBuhI38vqbnx5vAgOjfURfBLniZWX+eSJ2Mp8Z5uS+rBCbnBktEY/KPeRx5DCSDFU39SoDx6oinlMb5FPlONhfJ9xIVBb23S/8kMz6aP5Tu9ibE2W0IFUGE2emwSafIboXmpw/xzktlji0a/VLTYd1mTjZ58aXYpPRLl/voVz/NF9yxzpI4kH9guCuGr6Mww4SCeH1oUL2iAe4JKalkZmK2QW9qq5XCeB7v2gPsfgwTKVv/vwnhy5gL5QdGt7+BTrD7Gs8wE8SppEPSTPOUgt1FA1Fk2XgF0HkVAaqHVOa8pBx2rNcJ26CjnvIPRvz0YNd84nwkf1yUXI6C8ecdj8tJv3VhY4vQCvMEsrZa6Pqxh1SmzkmW6HK1zEHd7keQuscpturKEdfJd4gK9EH6XTG/3B2fzqlo251rbtXMUpqaf9bLvpGAEEGHmH6Vovuu0YIHbiynUbKg0g3aptB56zQWtmqdI5fsPdE23laFrBQv+W+CQzEYgLaI2ekvneccFJ700c1naOjEcZ94Oi2S2Kn+5TDIr13rlRYA+q5gYFhlRRDrMl1Jx35Y=
    on:
      branch: master
