dist: trusty
sudo: false
language: node_js
node_js:
  - '12'
addons:
  chrome: stable
cache:
  directories:
    - './node_modules'
install:
  - npm install
before_script:
  - npm install -g @ionic/cli
script:
  - npm run prebuild -- $TRAVIS_BRANCH
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    ionic build --configuration=staging;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ionic build --configuration=production;
    fi
before_deploy:
  - (cd functions && npm install)
deploy:
  - provider: firebase
    skip_cleanup: true
    message: Deploying LeCoinDuProf to STAGING
    project: default
    token:
      secure: '3dHXqWaUyiPrLPlCnoQJTC7On8NsO1/qS+/hNeUNvsVtAVLIU9aOoYsi3KhMbatxykh3nne/g/m7ensPrcGdSG6MhzxPzOVJQy4lMvU+T7P5vjJweTV8OW/dGRtIlzECrdy96VY1mlucnHqqTG7xgJpK2Buo4QUIjOIJUnyDZwkIhY8Fqt1Y/LFJaX2qAQg0d654PDPdbBXe9X7xBwzUAnq5SulSQwYPgbwC72mHLp8CRzp68A1dbAT23GnbyC4KvkrjdbhA2em3HA7RiHP4eI+IlE/fDQnAHjw1TB1WIGSMrpHV19LJ3uq+1TdT9lbv0mwEwEwvl8fc0FYaPG8cr8f/2zvm+qEQT/NH7e8rNKzt3OImHXX0dd9/183OFKn7Uotbzf1W5Dsuaa/ZFUoXmYQvr0kQH3Ze8vzBurMAZVMb/VKe2b0TB0rW1W5F6qdNo2EY1WEqrDf0WjT9R1bYmfatfumrXuNlReYcnUldajoVaTjn6J6MU/DaAiK3NxwbOMI7GSwwrPxF8TP8iVzSvdKQtfqRQCSZ37u62CgX5Mqf4GnABLygv0/V3eVWxWxfe7QEOLWWYwWmA2z2ZaFZXALR0p4BhPMmumq8h3KhSkbKOnt6Qsfw+Ii8CXJL8Kh5WZw1w2DTQZuMQhK9tr2Xbxztro2V+xMFupaQ2NmCyf0='
    on:
      branch: develop
  - provider: firebase
    message: Deploying LeCoinDuProf to PRODUCTION
    skip_cleanup: true
    project: production
    token:
      secure: '3dHXqWaUyiPrLPlCnoQJTC7On8NsO1/qS+/hNeUNvsVtAVLIU9aOoYsi3KhMbatxykh3nne/g/m7ensPrcGdSG6MhzxPzOVJQy4lMvU+T7P5vjJweTV8OW/dGRtIlzECrdy96VY1mlucnHqqTG7xgJpK2Buo4QUIjOIJUnyDZwkIhY8Fqt1Y/LFJaX2qAQg0d654PDPdbBXe9X7xBwzUAnq5SulSQwYPgbwC72mHLp8CRzp68A1dbAT23GnbyC4KvkrjdbhA2em3HA7RiHP4eI+IlE/fDQnAHjw1TB1WIGSMrpHV19LJ3uq+1TdT9lbv0mwEwEwvl8fc0FYaPG8cr8f/2zvm+qEQT/NH7e8rNKzt3OImHXX0dd9/183OFKn7Uotbzf1W5Dsuaa/ZFUoXmYQvr0kQH3Ze8vzBurMAZVMb/VKe2b0TB0rW1W5F6qdNo2EY1WEqrDf0WjT9R1bYmfatfumrXuNlReYcnUldajoVaTjn6J6MU/DaAiK3NxwbOMI7GSwwrPxF8TP8iVzSvdKQtfqRQCSZ37u62CgX5Mqf4GnABLygv0/V3eVWxWxfe7QEOLWWYwWmA2z2ZaFZXALR0p4BhPMmumq8h3KhSkbKOnt6Qsfw+Ii8CXJL8Kh5WZw1w2DTQZuMQhK9tr2Xbxztro2V+xMFupaQ2NmCyf0='
    on:
      branch: master
