dist: trusty
sudo: false
language: node_js
node_js:
  - '12'
addons:
  chrome: stable
cache:
  directories:
    - './node_modules'
install:
  - npm install
before_script:
  - npm install -g @ionic/cli
script:
  - npm run prebuild
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    ionic build --configuration=staging;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ionic build --configuration=production;
    fi
before_deploy:
  - (cd functions && npm install)
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    message: 'Deploying LeCoinDuProf to STAGING'
    project: default
    token: 'rTBbk54SSQXIEKfBlHN3JL0kOjdEcTRiWAYpoZB+sdza4eMvBRzESoxdFWZY7G5sWmY+ejY/X9xzvW+e2lUFKrNGFDoVnwwU+hCUlSFyrLabFfDqqHwAsmH35x6o1ut7WxPDqT9vALNvnM0f6xn1G9KR0mBW/iCsbOKPLUO9tIc0Y/jZahgvuuHigOR14rQiqPx13vxbk9o6XbDoVRWHMCci1yuaGvT8n0+49DnMg2WOwe+/p79oOhIn0awdaHlQPPW4xbMCLLnqWX2913SL/6rc9mklSQQS7wVAiUR6WazqmBx+NjMKy42ByEg/i2Q5u+LLsIjdkcoUQId9JjaSrWeRE/eka2ryedpi/X+wn9gfBk00p1LImwLBXWNsLxoTXOcPfqjevvyGMFkQkocd3hnxUeLHFsyZPLoitnFTGTxQtl7H/JDF3rlzx38g7+NyQf6tN9qePLrDuPkKWYeHjM2MYyVZxJEISmjYg+ZCD+PpOdEP5PvKniZuWin/ovd2KBK1ZRv3zE0+D23lE3Z5YTMznLwHnBjz7Oph94PG2njSRII4FwS1oiJ/2E5lf+PeDq87OK28drzSF2szmN8wkM13B4pMFWmmpm5iC6PKnCjs+YcqX/Sc5mwKy4YuGEYoFybL98Mfks9R7Y6+PvbM8UlWWcELnn7ksF18WcnJksA='
    on:
      branch: develop
  - provider: firebase
    message: 'Deploying LeCoinDuProf to PRODUCTION'
    skip_cleanup: true
    project: production
    token: 'rTBbk54SSQXIEKfBlHN3JL0kOjdEcTRiWAYpoZB+sdza4eMvBRzESoxdFWZY7G5sWmY+ejY/X9xzvW+e2lUFKrNGFDoVnwwU+hCUlSFyrLabFfDqqHwAsmH35x6o1ut7WxPDqT9vALNvnM0f6xn1G9KR0mBW/iCsbOKPLUO9tIc0Y/jZahgvuuHigOR14rQiqPx13vxbk9o6XbDoVRWHMCci1yuaGvT8n0+49DnMg2WOwe+/p79oOhIn0awdaHlQPPW4xbMCLLnqWX2913SL/6rc9mklSQQS7wVAiUR6WazqmBx+NjMKy42ByEg/i2Q5u+LLsIjdkcoUQId9JjaSrWeRE/eka2ryedpi/X+wn9gfBk00p1LImwLBXWNsLxoTXOcPfqjevvyGMFkQkocd3hnxUeLHFsyZPLoitnFTGTxQtl7H/JDF3rlzx38g7+NyQf6tN9qePLrDuPkKWYeHjM2MYyVZxJEISmjYg+ZCD+PpOdEP5PvKniZuWin/ovd2KBK1ZRv3zE0+D23lE3Z5YTMznLwHnBjz7Oph94PG2njSRII4FwS1oiJ/2E5lf+PeDq87OK28drzSF2szmN8wkM13B4pMFWmmpm5iC6PKnCjs+YcqX/Sc5mwKy4YuGEYoFybL98Mfks9R7Y6+PvbM8UlWWcELnn7ksF18WcnJksA='
    on:
      branch: master
